### ISSUE TITLE
PID-Test robot suddenly disappears from the course

### ISSUE THREAD

**Issue by lucassarten** [ruhaansaiyad/Team-7-AVC-Project#5]
Not sure whats causing this but the robot disappears every time it reaches this specific corner. Here's a vid of it running. https://i.imgur.com/uXJpnTp.gifv

**Comment by ruhaansaiyad** [comment]
Seems like the config file is not the same for server and robot. The camera view looks different from what it should be

**Comment by lucassarten** [comment]
That was it. Working perfectly now thanks!
